apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb1
  labels:
    type: app
    app-type: springboot
    env: dev
spec:
  template:
    spec:
      containers:
        - name: sb1
          image: legnoban/test-app-sb1:1.0.5
          env:
            - name: VISITOR
              value: 'Mr. Dev'