apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vcs
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: The app bundle POC project

  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - 'ssh://git@bitbucket.webbfontaine.com:7999/proto/vcs.git'

  # Only permit applications to deploy to the vcs-* namespace in the same cluster
  destinations:
    - namespace: 'vcs-eg-dev'
      server: '*'
    - namespace: 'vcs-eg-qa'
        server: '*'

  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'