apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: sb2-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
spec:
  entrypoint: full
  serviceAccountName: argo
  volumes:
  - name: kaniko-secret
    secret:
      secretName: regcred
      items:
        - key: .dockerconfigjson
          path: config.json
  templates:
  - name: full
    dag:
      tasks:
      - name: build-container-image
        templateRef:
          name: container-image
          template: build-kaniko-git
          clusterScope: true
        arguments:
          parameters:
          - name: repo_url
            value: git://github.com/letthefireflieslive/test-app-sb2
          - name: repo_ref
            value: refs/heads/main
          - name: container_image
            value: legnoban/test-app-sb2
          - name: container_tag
            value: "1.0.0"
