---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vs
spec:
  gateways:
    - istio-system/cluster-ingressgateway
  hosts:
    - devops.wfgmb.com
  http:
    - match:
        - uri:
            exact: /dev-sb1
      redirect:
        uri: /dev-sb1/
    - match:
        - uri:
            prefix: /dev-sb1/
      rewrite:
        uri: /
      route:
        - destination:
            host: sb1
            port:
              number: 8080
    - match:
        - uri:
            exact: /dev-sb2
      redirect:
        uri: /dev-sb2/
    - match:
        - uri:
            prefix: /dev-sb2/
      rewrite:
        uri: /
      route:
        - destination:
            host: sb2
            port:
              number: 8080