apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb2
  labels:
    app: sb2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sb2
  template:
    metadata:
      labels:
        app: sb2
    spec:
      containers:
        - name: sb2
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred