apiVersion: v1
kind: Secret
metadata:
  name: regcred
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXJodWIud2ZnbWIuY29tOjUwMDAiOnsidXNlcm5hbWUiOiJ0ZWFtY2l0eV9kZXZrdWJlIiwicGFzc3dvcmQiOiJGQkoqZmhjQGo3N1BaX3FAIiwiYXV0aCI6ImRHVmhiV05wZEhsZlpHVjJhM1ZpWlRwR1Frb3FabWhqUUdvM04xQmFYM0ZBIn19fQ==
type: kubernetes.io/dockerconfigjson