apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb2
  labels:
    type: app
    app-type: springboot
    env: dev
spec:
  template:
    spec:
      containers:
        - name: sb2
          image: legnoban/test-app-sb2:2.0.0
          env:
            - name: VISITOR
              value: 'Mr. Dev'