apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcs-dev
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  project: default
  source:
    repoURL: ssh://git@bitbucket.webbfontaine.com:7999/proto/vcs.git
    path: ./overlays/eg/dev/argo
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

