apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcs-dev
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  project: default
  source:
    repoURL: ssh://git@bitbucket.webbfontaine.com:7999/proto/vcs.git
    path: ./overlays/eg/dev/argo
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).

