apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcs-dev-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: ./overlays/eg/dev/**/argo.yml
    repoURL: ssh://git@bitbucket.webbfontaine.com:7999/proto/vcs.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: vcs-eg-dev
