apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: container-reg-creds
  namespace: vcs-eg-qa
spec:
  encryptedData:
    .dockerconfigjson: AgCph5wY9siXRCZydUrAVdl29ktsFprqjBf6Az5Qar5fjlZ5AilPEjvkHYXHwum6ugoz3UE8r9F2fod2WoFwgOQKGv4lzNqm6TEcjHbCEEQr5YbOnW9y6VKXdGwWTvljleqI5l47YCQgFucBecaLaGtSUkvxFhDAsYwD4kZGQ1+3zDszqiXJ/Lejkf3n29nZ0GHpYwkac0KtZ/7WNpr6wIqsDB3c2CL9LN1GZGrNrudJfo8fOMQUplrlS6O0D194Q2vyq6S7zJdD7cnT+tXh27p5i0GlLVN0cRyFq5yzA4WjGDbo1pdmYDUJe6ln16L4DAMt+3RAWlk17ITc4He2V35OMi53K3ETDRBvk7qAPcK9O9ib9nssF+FIgf5P5rrfmVe4SvB5UdHPG03oZOodSN5RRR2b/MDxuDe6U8WQOSR2NfZnzHHAi0xiecTCyJd1Wb/mOssWA4oif1/2jJIcVHbYs47bq/b7efGSgPzH9M644PS1n9+/AgdPatbc9xIC4j21uxFUiIZ/7GtRZUUbZcxu3nopVCiYKmyls4+ZTbHGpt1QdNpjaAxiyWnyoyX9+XEgITZSzGA7E2nfAiaRKeHOJeDeRNZdI2yEXz5lqlaPC6jUASV13GZfxHIXKSVy+sR/7Jypmra9cFU8SsOCDv0xrZ8qqSFfve5XsJMMOYS2Ozwpf3n8XQEkUcJEItd/TAu01IkIUeuoEl6W4C/yvDpvL5b+tbC0geViC1fBEzZTfqYFvDXv4hzDupOvAokOL5I4HGbXsXUoDQB3Zar271R7/SHdH7hihH3jvDuKagxUpg203ho0/wEtTHK3ZDbwhekY49RNCatwdoyVv7mKv/VGlgr6g8JgJxxb8RVVd387juzHB5VQeUWiwsDmr2Z0F5LYsywJNDgu
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: container-reg-creds
      namespace: vcs-eg-qa
    type: kubernetes.io/dockerconfigjson

